### ISSUE TITLE
Implement outstanding XIM scenarios

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/TitanTwo#40]
Placeholder.

Missing a few, e.g. authenticating reliably via T2 instead of XIM using a non-ps3 pad.

Boosting reliability on PS4.

etc.

**Comment by J2Kbr** [comment]
Hi Pablo. I am doing some tests with XIM4 (latest firmware) - right now checking on PS4. I am making an list of troubleshooting procedures and suggestions - so far there are two main issues I could detect:

1. Cables
2. Lack of Power

Please give me some problematic usage/connections, so I can reproduce and fix. Thanks.

Despite that, some users are reporting purple light with PS4 - I am unable to reproduce that. Not sure if the recent changes on the firmware (not released yet) solved this issue, or if it is something else on user's end (i.e. cable/lack of power). When you use XIM4+TitanTwo on PS4, do you get purple lights?

**Comment by J2Kbr** [comment]
Okay, purple lights are solved with the latest XIM4 firmware. Please disregard the above question on this matter. Thanks.

**Comment by GarethWright** [comment]
The unreleased one or  20170103?

**Comment by J2Kbr** [comment]
I testing with the version from 20170103.

**Comment by GarethWright** [comment]
Roger that. I've bought a powered hub to sit between the XIM and the keyboard and mouse as I'm still getting purple lights on XB1. I'll test that tonight.

**Comment by J2Kbr** [comment]
Improvements with the compatibility with XIM4 were noticed since the latest firmware. Reference:
https://www.consoletuner.com/forum/viewtopic.php?f=27&t=5224&start=180#p49677
If any other issue with XIM4 is noticed, please reopen.
